- name: Creating User server
  hosts: all
  become: yes
  tasks:
    - name: Downloading Nodejs Repo
      ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash
    - name: Installing nodejs Server
      ansible.builtin.yum:
        name: nodejs
        state: latest

    - name: Adding User
      ansible.builtin.user:
        name: roboshop

    - name: Remove the Directory
      ansible.builtin.file:
        path: /app
        state: absent

    - name: Create a directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Downloading new app content
      ansible.builtin.unarchive:
        src: https://roboshop-artifacts.s3.amazonaws.com/user.zip
        dest: /app
        remote_src: yes

    - name: Installing NodeJs Dependencies
      ansible.builtin.shell: npm install
      args:
        chdir: /app

    - name: Copying Service File and starting the service
      ansible.builtin.copy:
        src: catalogue.service
        dest: /etc/systemd/system/user.service

    - name: copy Mongodb repo
      ansible.builtin.copy:
       src: mongodb.repo
       dest: /etc/yum.repos.d/mongodb.repo

    - name: Install mongodb_schema
      ansible.builtin.yum:
        name: mongodb-org-shell
        state: latest

    - name: Loading Schema
      ansible.builtin.shell: mongo --host mongodb-dev.sadguru.shop </app/schema/user.js

    - name: Enabling and restarting user Server
      ansible.builtin.systemd:
        state: restarted
        name: user
        enabled: true
        daemon_reload: true

